hmcts/vh-automation-test

UI/Selenium/Hooks/Hooks.cs
UI/Selenium/UI.csproj
UI/Selenium/Utilities/EnvironmentConfigSettings.cs
UI/Selenium/Utilities/Util.cs
UI/Selenium/appsettings.json

Images captured - will be placed in a directory for each test. 
The name of the directory will be the same as the name of log file generated for the tet run

Place images and Reports in a directory for each test

---

UI/Selenium/Features/Web Features/EndtoEnd.feature
UI/Selenium/Hooks/Hooks.cs
UI/Selenium/Model/SauceLabsOptions.cs
UI/Selenium/UI.csproj
UI/Selenium/Utilities/DriverFactory.cs
UI/Selenium/Utilities/EnvironmentConfigSettings.cs
UI/Selenium/appsettings.json

Support for SauceLabs integration

Support or SauceLabs integration

---

UI/Selenium/Steps/LoginPageSteps.cs
UI/Selenium/UI.csproj
UI/Selenium/Utilities/DriverFactory.cs

add missing TextCopy NuGet package

added back the Saucelabs driver code

---

UI/Selenium/Features/Web Features/QuickLink.feature
UI/Selenium/Steps/LoginPageSteps.cs

Resolved merge conflicts for Quicklink to join hearing

---

TestFramework/ExtensionMethods.cs
UI/Selenium/Hooks/Hooks.cs
UI/Selenium/Pages/ParticipantsPage.cs
UI/Selenium/Steps/CommonActions/LogoffSteps.cs
UI/Selenium/Steps/HearingRoomSteps.cs
UI/Selenium/Steps/ParticipantsSteps.cs
UI/Selenium/Steps/SummaryPageSteps.cs

Address bug for VHO not closing
Address bug for VHO getting signed out when entering participant details

Fixes vho browser not closing

---

API/RestSharpAPI/Properties/launchSettings.json
API/RestSharpAPI/appsettings.json
TestFramework.sln
UI/Selenium/Properties/launchSettings.json

Set to use Acceptance / AAT by default, not development which should **only** be done when there is a code version or environment issue.

Change default environment to be AAT not dev

---

TestFramework/ExtensionMethods.cs
UI/Selenium/Features/Web Features/WaitingRoom.feature
UI/Selenium/Pages/ParticipantWaitingRoomPage.cs
UI/Selenium/Steps/BookingListSteps.cs
UI/Selenium/Steps/CommonActions/LogoffSteps.cs
UI/Selenium/Steps/ConsultationRoomSteps.cs
UI/Selenium/Steps/HearingListSteps.cs
UI/Selenium/Steps/HearingRoomSteps.cs
UI/Selenium/Steps/WaitingRoomPageSteps.cs

Checks the judge and participants have the correct status in the waiting room

Waiting room statuses

---

UI/Selenium/Hooks/Hooks.cs

fixes issues with tear down

---

UI/Selenium/Steps/BookingListSteps.cs

fix failing test CheckBookingListContainsExpectedValues

---

UI/Selenium/Steps/ParticipantsSteps.cs

Clear the organisation field

---

TestFramework/ExtensionMethods.cs
UI/Selenium/Features/Web Features/AccessibilityVideoWeb.feature
UI/Selenium/Features/Web Features/ConsultationRoom.feature
UI/Selenium/Model/Hearing.cs
UI/Selenium/Pages/ConsultationRoomPage.cs
UI/Selenium/Pages/HearingListPage.cs
UI/Selenium/Pages/JudgeWaitingRoomPage.cs
UI/Selenium/Steps/CreateHearingDetails.cs
UI/Selenium/Steps/DashboardSteps.cs
UI/Selenium/Steps/HearingListSteps.cs
UI/Selenium/Steps/LoginPageSteps.cs
UI/Selenium/Steps/SelectYourHearingListSteps.cs
UI/Selenium/Steps/WaitingRoomPageSteps.cs
UI/Selenium/Utilities/ObjectFactory.cs

Adds tests for VHO starting a consultation with a judge, and closing the consultation

Consultation room vho can start close consultation

---

TestFramework/ExtensionMethods.cs
UI/Selenium/Features/Web Features/ConsultationRoom.feature
UI/Selenium/Pages/HearingListPage.cs
UI/Selenium/Steps/HearingListSteps.cs
UI/Selenium/Steps/WaitingRoomPageSteps.cs
UI/Selenium/Utilities/ObjectFactory.cs

VHO IM implementation

---

UI/Selenium/Features/Web Features/BookingList.feature
UI/Selenium/Pages/BookingDetailsPage.cs
UI/Selenium/Pages/BookingListPage.cs
UI/Selenium/Steps/BookingListSteps.cs

vho search booking by case-type

---

UI/Selenium/Steps/CheckAlertsCommandCenterSteps.cs

Fixes check alert tests not closing after test run

Improve accessibility tests

---

UI/Selenium/Steps/BookingListSteps.cs

Small fix for JoinByTelephoneNumbers are correct feature

---

TestFramework/ExtensionMethods.cs
UI/Selenium/Features/Web Features/CheckAlertsToCommandCentre.feature
UI/Selenium/Features/Web Features/CheckParticipantStatusToCommandCentre.feature
UI/Selenium/Features/Web Features/EndtoEnd.feature
UI/Selenium/Features/Web Features/JoinByTelephone.feature
UI/Selenium/Features/Web Features/QuickLink.feature
UI/Selenium/Hooks/Hooks.cs
UI/Selenium/Pages/ConsultationRoomPage.cs
UI/Selenium/Pages/ParticipantHearingListPage.cs
UI/Selenium/Steps/BookingListSteps.cs
UI/Selenium/Steps/CheckAlertsCommandCenterSteps.cs
UI/Selenium/Steps/CheckParticipantStatusToCommandCentreSteps.cs
UI/Selenium/Steps/CommonActions/LogoffSteps.cs
UI/Selenium/Steps/ConsultationRoomSteps.cs
UI/Selenium/Steps/HearingListSteps.cs
UI/Selenium/Steps/LoginPageSteps.cs
UI/Selenium/Steps/SummaryPageSteps.cs
UI/Selenium/Steps/WaitingRoomPageSteps.cs
UI/Selenium/Utilities/DriverFactory.cs
UI/Selenium/Utilities/ObjectFactory.cs

Fix some issues

---

UI/Selenium/Steps/ConsultationRoomSteps.cs
UI/Selenium/Steps/HearingRoomSteps.cs
UI/Selenium/Steps/WaitingRoomPageSteps.cs

fix consultation_room tests

---

API/RestSharpAPI/Steps/SimpleApiSteps.cs
TestFramework/ExtensionMethods.cs
UI/Selenium/Hooks/Hooks.cs
UI/Selenium/Pages/SummaryPage.cs
UI/Selenium/Steps/SummaryPageSteps.cs
UI/Selenium/Steps/WaitingRoomPageSteps.cs

Code cleanup
QuickFix book and confirm
code clean

QuickFix book and confirm

---

TestFramework/TestFramework.csproj
UI/Selenium/UI.csproj

DO NOT APPROVE - check dependabot fix

---

API/RestSharpAPI/Features/BookingsApi.feature
API/RestSharpAPI/SwaggerJsonApi.csproj

Remove Healthcheck
Remove LaunchDarkly dependency
```
[ ] Yes
[ ] No
```

Code Cleanup

---

Dockerfile
TestFramework.sln

Docker update

---

Documentation for Framework/Readme.txt

zerosum change - test dependabot

---

.gitignore
UI/Selenium/Features/Web Features/AccessibilityVideoAdmin.feature
UI/Selenium/Features/Web Features/AccessibilityVideoWeb.feature
UI/Selenium/Features/Web Features/BookingList.feature
UI/Selenium/Features/Web Features/CheckAlertsToCommandCentre.feature
UI/Selenium/Features/Web Features/CheckParticipantStatusToCommandCentre.feature
UI/Selenium/Features/Web Features/ConsultationRoom.feature
UI/Selenium/Features/Web Features/GetAudioFile.feature
UI/Selenium/Features/Web Features/HearingRoomControls.feature
UI/Selenium/Features/Web Features/JudgeInviteParticipant.feature
UI/Selenium/Features/Web Features/WaitingRoom.feature

Change of tags for pipelines

---

API/RestSharpAPI/Steps/BookingsApiSteps.cs
API/RestSharpAPI/SwaggerJsonApi.csproj
API/RestSharpAPI/Utilities/TestConfigHelper.cs
UI/Selenium/Utilities/TestConfigHelper.cs

https://tools.hmcts.net/jira/browse/VIH-9181
fixing path for mac

VIH-9181 - fixing path for Mac

---

CODEOWNERS
UI/Selenium/Features/Web Features/AccessibilityVideoAdmin.feature
UI/Selenium/Features/Web Features/EndtoEnd.feature
UI/Selenium/Pages/SelectHearingPage.cs
UI/Selenium/Properties/launchSettings.json
UI/Selenium/Steps/BookingListSteps.cs
UI/Selenium/Steps/HearingScheduleSteps.cs
UI/Selenium/Steps/SelectHearingSteps.cs
UI/Selenium/UI.csproj
UI/Selenium/Utilities/EnvironmentConfigSettings.cs
UI/Selenium/Utilities/TestConfigHelper.cs
UI/Selenium/appsettings.json

###VIH-8633 ###
Changes made to:
- app config - telephone number 
- fixed tests, improved implementation
- yaml file
###
```
[ ] Yes
[ x] No
```

VIH-8633 Update End2EndTests

---

UI/Selenium/Features/Web Features/AccessibilityVideoAdmin.feature
UI/Selenium/Pages/DashboardPage.cs
UI/Selenium/Pages/WorkAllocation.cs
UI/Selenium/Steps/AccessibilitySteps_ParticipantsHearingSignIn.cs
UI/Selenium/Steps/AccessibilitySteps_VideoBooking.cs

https://tools.hmcts.net/jira/browse/VIH-9564
changes to ignore minor aXE Violations ###
```
[ ] Yes
[ x] No
```

VIH-9552 Work allocation accessibility test and Ignore minor aXE violation 

---

TestFramework/ExtensionMethods.cs
UI/Selenium/Hooks/Hooks.cs
UI/Selenium/Steps/AccessibilitySteps_VideoBooking.cs
UI/Selenium/Steps/HearingAssignJudgeSteps.cs
UI/Selenium/Steps/HearingScheduleSteps.cs
UI/Selenium/Utilities/DateFormats.cs
UI/Selenium/Utilities/DriverFactory.cs
UI/Selenium/Utilities/TestConfigHelper.cs
UI/Selenium/appsettings.json

VIH-9623
* Fix date input format when running in saucelabs
* Update test journey for bookings details
* Capture exception for missing elements instead of null object
```
[ ] Yes
[x] No
```

VIH-9623 Fix date input format

---

azure-pipelines.sds.nightly.yml
azure-pipelines.sds.release.yml

N/A
Run e2e tests for nightly
```
[ ] Yes
[x] No
```

VIH-0000 Setup nightly tests

---

azure-pipelines.sds.nightly.yml

N/A
Adding a pipeline timeout statement to increase the default time limit on the pipeline run.
```
[ ] Yes
[X ] No
```

VIH-0000 Increase nightly pipeline timeout

---

UI.NUnitVersion/Admin/WorkAllocation/ManageTeamTests.cs
azure-pipelines.sds.daily.yml

N.A
rename new nightly to 'daily' and set to 8am daily since the Wowza VMs are turned off overnight
```
[ ] Yes
[x] No
```

Update schedule for new daily build

---

UI.NUnitVersion/Admin/GetAudioLink/GetVideoHearingAudioLinkTests.cs
UI.PageModels/Pages/Admin/Audio/GetAudioFilePage.cs
UI.PageModels/Pages/Admin/Booking/HearingSchedulePage.cs
UI.PageModels/Pages/Admin/DashboardPage.cs
UI.PageModels/Pages/Admin/WorkAllocation/AllocateJusticeUserToHearingSection.cs
UI.PageModels/Pages/Admin/WorkAllocation/EditHoursSection.cs
UI.PageModels/Pages/Admin/WorkAllocation/ManageTeamSection.cs
UI.PageModels/Pages/Admin/WorkAllocation/UploadHoursSection.cs
UI.PageModels/Pages/VhPage.cs
UI.PageModels/UI.PageModels.csproj
azure-pipelines.sds.daily.yml

VIH-9980
* add audio retrieval UI test
* fix bug regarding time and date format when running on saucelabs
* update daily schedule to 9:15am BST
* replace assertions with if-checks-and-exceptions in Page Object Models
```
[ ] Yes
[x] No
```

VIH-9980 add audio retrieval test

---

UI.NUnitVersion/TestData/HearingTestData.cs
UI.NUnitVersion/Video/EndToEndTest.cs
UI.PageModels/Pages/Admin/WorkAllocation/EditHoursSection.cs
UI.PageModels/Pages/Admin/WorkAllocation/ManageWorkAllocationPage.cs
UI.PageModels/Pages/VhVideoWebPage.cs
UI.PageModels/Pages/Video/VideoWebLogoutPage.cs

VIH-9723
Assert logout page after signing out in video web
```
[ ] Yes
[x] No
```

VIH-9723 Assert logout page after signing out in video web

---

UI.NUnitVersion/Admin/Booking/BookHearingTests.cs
UI.NUnitVersion/Drivers/RemoteChromeVhDriver.cs
UI.PageModels/Pages/Admin/WorkAllocation/ManageTeamSection.cs
UI.PageModels/Pages/VhPage.cs

N/A
Update Test Setup and Assertion
```
[ ] Yes
[x] No
```

Update Test Setup and Assertion

---

UI/Selenium/UI.csproj
azure-pipelines.sds.release.yml

VIH-9897-AutoPipelineTest1

---

UI.NUnitVersion/Admin/Booking/BookHearingTests.cs
UI.NUnitVersion/TestData/HearingTestData.cs
UI.PageModels/Dtos/BookingDto.cs
UI.PageModels/Dtos/BookingExistingParticipantDto.cs
UI.PageModels/Pages/Admin/Booking/VideoAccessPointsPage.cs

VIH-9985
Update the book a hearing test to include video access points
```
[ ] Yes
[x] No
```

VIH-9985 Update the book a hearing test to include video access points

---

API/RestSharpAPI/Steps/BookingsApiSteps.cs
API/RestSharpAPI/Steps/UserApiSteps.cs
API/RestSharpAPI/SwaggerJsonApi.csproj
UI.Common/Configuration/ApiClientConfiguration.cs
UI.Common/Configuration/ConfigRootBuilder.cs
UI.Common/Security/TokenProvider.cs
UI.Common/UI.Common.csproj
UI.NUnitVersion/Admin/AdminWebUITest.cs
UI.NUnitVersion/Admin/Booking/BookHearingTests.cs
UI.NUnitVersion/UI.NUnitVersion.csproj
UI.NUnitVersion/VhApiClientFactory.cs
UI.NUnitVersion/appsettings.json
UI.PageModels/Pages/Admin/WorkAllocation/UploadHoursSection.cs
azure-pipelines.sds.daily.yml
global.json
nuget.config

N/A
Add API Client to NUnit project so that tests clean up can invoke the remove hearing endpoint
```
[ ] Yes
[x] No
```

Add api clients

---

UI.NUnitVersion/Admin/Booking/BookHearingTests.cs
UI.NUnitVersion/Admin/Booking/EditBookingTest.cs
UI.NUnitVersion/GlobalUsings.cs
UI.NUnitVersion/TestData/HearingTestData.cs
UI.NUnitVersion/Video/EndToEndTest.cs
UI.NUnitVersion/Video/QuickLinkUserTests.cs
UI.NUnitVersion/Video/VHO/VhoLearning.cs
UI.NUnitVersion/appsettings.json
UI.PageModels/GlobalUsings.cs
UI.PageModels/Pages/Admin/Booking/BookingConfirmationPage.cs
UI.PageModels/Pages/Admin/Booking/BookingDetailsPage.cs
UI.PageModels/Pages/Admin/Booking/HearingDetailsPage.cs
UI.PageModels/Pages/Admin/Booking/HearingSchedulePage.cs
UI.PageModels/Pages/Admin/Booking/ParticipantsPage.cs
UI.PageModels/Pages/Admin/Booking/SummaryPage.cs
UI.PageModels/Pages/Admin/Booking/VideoAccessPointsPage.cs
UI.PageModels/Pages/Video/Vho/CommandCentrePage.cs
UI.PageModels/Pages/Video/Vho/VhoVenueSelectionPage.cs

VIH-10070
VIH-10072
* Add edit tests to cover the scenarios:
* Book hearing with judge only. Then add participants after booking
* Book a hearing with judge, participants and linked video access points. Then update schedule
* Remove created hearings as a part of a test tear down 
* Update the page object models to reduce code for booking found in multiple test files
```
[ ] Yes
[x] No
```

Add Edit hearing tests

---

UI.NUnitVersion/Admin/Booking/BookHearingTests.cs
UI.PageModels/Pages/Admin/Booking/SummaryPage.cs

TBC
Update validation assertions between summary and details page
```
[ ] Yes
[x] No
```

VIH-0000 Update validation assertions between summary and details page

---

UI.Common/Configuration/ConfigRootBuilder.cs
UI.Common/Configuration/TestDataConfiguration.cs
UI.NUnitVersion/Admin/AdminWebUITest.cs
UI.NUnitVersion/Admin/GetAudioLink/GetVideoHearingAudioLinkTests.cs
UI.NUnitVersion/Drivers/RemoteChromeVhDriver.cs
UI.NUnitVersion/Utilities/BuildName.cs
UI.NUnitVersion/Video/VideoWebUiTest.cs
UI.NUnitVersion/appsettings.json
azure-pipelines.sds.daily.yml
azure-pipelines.sds.regression.yml
variables/dev.yaml
variables/stg.yaml

VIH-10083
Enable test suite data to be configurable
Add environment name to saucelabs build name
```
[ ] Yes
[x] No
```

VIH-10083 Add test data config to be env agnostic

---

GitVersion.yml
UI.NUnitVersion/Admin/GetAudioLink/GetVideoHearingAudioLinkTests.cs
azure-pipelines.sds.daily.yml
azure-pipelines.sds.regression.yml
pipelines/templates/run-ui-test.yaml
variables/shared.yaml

VIH-10083
Add missing var for the accessibility job
Move more variables into the shared group to simplify jobs
```
[ ] Yes
[x] No
```

VIH-10083 Fix a11y job

---

UI.NUnitVersion/TestData/HearingTestData.cs
UI.PageModels/Pages/VhPage.cs
UI.PageModels/Pages/Video/Participant/JudgeWaitingRoomPage.cs
UI.PageModels/Pages/Video/Participant/ParticipantWaitingRoomPage.cs

VIH-9985
Update test setup and page wait time for ParticipantWaitingRoomPage.cs
```
[ ] Yes
[x] No
```

VIH-9985 Update test setup and page wait time for ParticipantWaitingRoomPage.cs

---

UI.NUnitVersion/Admin/AdminWebUITest.cs
UI.NUnitVersion/Admin/Booking/EditBookingTest.cs
UI.NUnitVersion/GlobalUsings.cs
UI.NUnitVersion/UI.NUnitVersion.csproj
UI.PageModels/Pages/Video/Participant/CheckEquipmentPage.cs
UI.PageModels/Pages/Video/Participant/ConsultationRoomPage.cs
UI.PageModels/Pages/Video/Participant/CourtRulesPage.cs
UI.PageModels/Pages/Video/Participant/DeclarationPage.cs
UI.PageModels/Pages/Video/Participant/GetReadyForTheHearingIntroductionPage.cs
UI.PageModels/Pages/Video/Participant/JudgeHearingListPage.cs
UI.PageModels/Pages/Video/Participant/JudgeHearingRoomPage.cs
UI.PageModels/Pages/Video/Participant/MicrophoneWorkingPage.cs
UI.PageModels/Pages/Video/Participant/ParticipantHearingRoomPage.cs
UI.PageModels/Pages/Video/Participant/ParticipantWaitingRoomPage.cs
UI.PageModels/Pages/Video/Participant/SeeAndHearVideoPage.cs
UI.PageModels/Pages/Video/Participant/SelectHearingPage.cs
UI.PageModels/Pages/Video/Participant/StaffMemberHearingListPage.cs
UI.PageModels/Pages/Video/Participant/SwitchOnCameraMicrophonePage.cs
UI.PageModels/Pages/Video/Participant/TestingEquipmentPage.cs
UI.PageModels/Pages/Video/QuickLink/QuickLinkHearingListPage.cs
UI.PageModels/Pages/Video/QuickLink/QuickLinkJoinYourHearingPage.cs
UI/Selenium/UI.csproj

VIH-9985
Update bookings api client
Check page has finished loading before running a11y checks
```
[ ] Yes
[ ] No
```

VIH-9985 Update client and tests

---

UI.NUnitVersion/Admin/WorkAllocation/WorkHourTests.cs

VIH-10148
Add clean up for work hours
```
[ ] Yes
[x] No
```

VIH-10148 Add test clean up for work hours

---

UI.PageModels/Pages/VhPage.cs

[VIH-9985](https://tools.hmcts.net/jira/browse/VIH-9985)
use else if to avoid secondary condition to run
```
[ ] Yes
[x] No
```

VIH-9985 use else if to avoid secondary condition to run

---

UI.NUnitVersion/Models/VideoWebParticipant.cs
UI.NUnitVersion/TestData/HearingTestData.cs
UI.NUnitVersion/Video/EndToEndTest.cs
UI.NUnitVersion/Video/StaffMemberTests.cs
UI.NUnitVersion/Video/VideoWebUiTest.cs
UI.PageModels/Pages/Video/Participant/StaffMemberHearingListPage.cs
UI.PageModels/Pages/Video/Participant/StaffMemberVenueListPage.cs
UI.PageModels/Pages/Video/Participant/StaffMemberWaitingRoomPage.cs
UI.PageModels/Pages/Video/VideoWebLoginPage.cs
azure-pipelines.sds.daily.yml
azure-pipelines.sds.regression.yml

https://tools.hmcts.net/jira/browse/VIH-10211
Added staffmember test
Tested in SauceLabs: https://app.eu-central-1.saucelabs.com/tests/1f6a1243f60440bcb6a4106f3828aead

VIH-10211 Created StaffMember test scenario and pagemodels

---

UI.NUnitVersion/Video/EndToEndTest.cs
UI.NUnitVersion/Video/JudgeTests.cs
UI.NUnitVersion/Video/StaffMemberTests.cs
UI.PageModels/Pages/Video/Participant/JudgeWaitingRoomPage.cs

https://tools.hmcts.net/jira/browse/VIH-10231
Update tests with display name editing for judge and staff member
Tests passed in SauceLabs:
https://app.eu-central-1.saucelabs.com/tests/35484950f82f4aa690e3bbc474d814a8
https://app.eu-central-1.saucelabs.com/tests/79bcf30223c9453c92ed83f89aa65b4e#26
https://app.eu-central-1.saucelabs.com/tests/4d23543e85f647b4b5e8a3a16c139911#24

VIH-10231 Judge or staff member edits own display name in waiting room

---

UI.Common/Configuration/ApiClientConfiguration.cs
UI.NUnitVersion/Drivers/RemoteChromeVhDriver.cs
UI.NUnitVersion/VhApiClientFactory.cs
UI.NUnitVersion/appsettings.json
azure-pipelines.sds.daily.yml
azure-pipelines.sds.regression.yml
pipelines/templates/run-ui-test.yaml

TBC
The app settings need to be a flat structure to avoid variables being mistaken for another section

VIH-0000 fix build issues

---

UI.PageModels/Pages/Admin/Booking/AddJudicialOfficeHoldersPage.cs
UI.PageModels/Pages/Admin/Booking/HearingAssignJudgePage.cs

VIH-10086
Create a Page Object Model for the new Add JoH page. Complete with add presiding judge, add panel member and continue
Tests will need to be updated accordingly to use the new journey and to also use ejud usernames

VIH-10086 Add the AddJudicialOfficeHoldersPage.cs

---

UI.NUnitVersion/Admin/Booking/BookHearingNoJohTests.cs
UI.NUnitVersion/Admin/Booking/BookHearingTests.cs
UI.NUnitVersion/Admin/Booking/EditBookingTest.cs
UI.NUnitVersion/Video/AddParticipantsPostBookingTests.cs
UI.NUnitVersion/Video/EndToEndTest.cs
UI.NUnitVersion/Video/QuickLinkUserTests.cs
UI.NUnitVersion/appsettings.json
UI.PageModels/Pages/Admin/Booking/BookingConfirmationPage.cs
UI.PageModels/Pages/Admin/Booking/BookingDetailsPage.cs
UI.PageModels/Pages/Admin/Booking/HearingAssignJudgePage.cs
UI.PageModels/Pages/Admin/Booking/HearingDetailsPage.cs
UI.PageModels/Pages/Admin/Booking/ParticipantsPage.cs
UI.PageModels/Pages/VhPage.cs
azure-pipelines.sds.daily.yml

https://tools.hmcts.net/jira/browse/VIH-10449
Refactored and simplified everything around 'adding participants' aswell as nuances between v1 and v2 toggled logic. Now passes alot more consistently Have also set date for daily's to run at midday, to see how SauceLabs handles it

VIH-10449 Flakey tests refactor

---

UI.NUnitVersion/Admin/Booking/BookHearingNoJohTests.cs
UI.NUnitVersion/Admin/Booking/BookHearingTests.cs
UI.NUnitVersion/Admin/Booking/CreatingMultiDayHearingTests.cs
UI.NUnitVersion/TestData/HearingTestData.cs
UI.PageModels/Dtos/BookingDto.cs
UI.PageModels/Pages/Admin/Booking/HearingAssignJudgePage.cs
UI.PageModels/Pages/Admin/Booking/HearingDetailsPage.cs
UI.PageModels/Pages/Admin/Booking/HearingSchedulePage.cs
UI.PageModels/Pages/Admin/Booking/SummaryPage.cs
UI.PageModels/Pages/VhAdminWebPage.cs
UI/Selenium/Pages/SummaryPage.cs
azure-pipelines.sds.daily.yml

https://tools.hmcts.net/jira/browse/VIH-10420
Created Multi-day booking test

VIH-10420 creating multi day bookings automation test

---

UI.NUnitVersion/Video/AddParticipantsPostBookingTests.cs
UI.NUnitVersion/Video/EndToEndTest.cs
UI.NUnitVersion/Video/JudgeTests.cs
UI.NUnitVersion/Video/QuickLinkUserTests.cs
UI.NUnitVersion/Video/StaffMemberTests.cs
UI.NUnitVersion/Video/VideoWebUiTest.cs

https://tools.hmcts.net/jira/browse/VIH-10477

VIH-10477 Conference details polling

---

UI.AutomationTests/Admin/AdminWebUITest.cs
UI.AutomationTests/Admin/Booking/BookHearingNoJohTests.cs
UI.AutomationTests/Admin/Booking/EditMultiDayHearingTests.cs
UI.AutomationTests/Admin/GetAudioLink/GetVideoHearingAudioLinkTests.cs
UI.AutomationTests/TestData/HearingTestData.cs
UI.AutomationTests/Utilities/FeatureToggles.cs
UI.AutomationTests/Video/VideoWebUiTest.cs
UI.PageModels/Pages/Admin/Booking/BookingDetailsPage.cs
UI.PageModels/Pages/Admin/Booking/HearingDetailsPage.cs
UI.PageModels/Pages/Admin/Booking/HearingSchedulePage.cs
UI.PageModels/Pages/Admin/Booking/OtherInfoPage.cs
UI.PageModels/Pages/Admin/Booking/ParticipantsPage.cs
UI.PageModels/Pages/Admin/Booking/SummaryPage.cs
UI.PageModels/Pages/Admin/Booking/VideoAccessPointsPage.cs

https://tools.hmcts.net/jira/browse/VIH-10421
- Add test for editing a single day of a multi-day hearing
- Add test for editing multiple days of a multi-day hearing

VIH-10421 Add tests for editing multi day bookings

---

UI.AutomationTests/Admin/Booking/CancelHearingTests.cs
UI.AutomationTests/Admin/Booking/CancelMultiDayHearingTests.cs
UI.AutomationTests/Admin/Booking/EditBookingTest.cs
UI.AutomationTests/Admin/Booking/EditMultiDayHearingTests.cs
UI.AutomationTests/Admin/Booking/HearingTest.cs
UI.AutomationTests/Admin/Booking/MultiDayHearingTest.cs
UI.PageModels/Constants/CancellationReasons.cs
UI.PageModels/Pages/Admin/Booking/BookingDetailsPage.cs

https://tools.hmcts.net/jira/browse/VIH-10518
https://tools.hmcts.net/jira/browse/VIH-10418
- Adds tests for cancelling single day and multi day hearings
- Refactoring of some existing tests

VIH-10518 Add tests for cancelling hearings

---

azure-pipelines.sds.daily.yml
pipelines/templates/run-ui-test.yaml

[VIH-10741](https://tools.hmcts.net/jira/browse/VIH-10741)

VIH-10741 install dotnet sdk version

---

UI.AutomationTests/Admin/Booking/EditMultiDayHearingTests.cs
UI.PageModels/Pages/Admin/Booking/VideoAccessPointsPage.cs

VIH-10745
Refactor the edit/remove methods

VIH-10745 update video access points page model (#232)

---

UI.AutomationTests/UI.AutomationTests.csproj
UI.PageModels/Pages/Video/Participant/JudgeWaitingRoomPage.cs
UI.PageModels/Pages/Video/Participant/ParticipantWaitingRoomPage.cs
UI.PageModels/UI.PageModels.csproj
pipelines/templates/run-ui-test.yaml

VIH-10840
Revert temp solution of refreshing on the waiting room page. The issue was with our handler, not the supplier

VIH-10840 Remove refresh as temp workaround for broken event handlers

---

UI.AutomationTests/Admin/AdminWebUITest.cs
UI.AutomationTests/Admin/WorkAllocation/WorkHourTests.cs
UI.AutomationTests/Video/JudgeTests.cs
UI.AutomationTests/Video/StaffMemberTests.cs
UI.PageModels/Pages/Admin/Booking/HearingSchedulePage.cs
UI.PageModels/Pages/Video/Vho/DashboardCommandCentre/CommandCentreHearingPanel.cs

https://tools.hmcts.net/jira/browse/VIH-10840
- Seed team leader justice user
- Remove wait for clickable for checkboxes (causes issues)
- Wait before checking updated display name

VIH-10840 Fix failing tests

---

UI.PageModels/Pages/Admin/Booking/BookingDetailsPage.cs
UI.PageModels/Pages/Admin/Booking/SpecialMeasuresPage.cs
UI.PageModels/Pages/Admin/Booking/VideoAccessPointsPage.cs

https://tools.hmcts.net/jira/browse/VIH-10840

VIH-10840 Fix navigation issues when in edit mode

---

UI.AutomationTests/Video/AddParticipantsPostBookingTests.cs
UI.AutomationTests/Video/EndToEndTest.cs
UI.AutomationTests/Video/JudgeTests.cs
UI.AutomationTests/Video/QuickLinkUserTests.cs
UI.PageModels/Pages/Video/Participant/JudgeHearingRoomPage.cs
UI.PageModels/Pages/Video/Participant/ParticipantHearingRoomPage.cs

https://tools.hmcts.net/jira/browse/VIH-10840
- Change div to button to match the updated UI
- Wait for countdown to complete before pausing the hearing
- Add scenario for pausing the hearing during the countdown

VIH-10840 Additional test fixes

---

README.md
UI.AutomationTests/Admin/Booking/BookHearingNoJohTests.cs
UI.AutomationTests/Admin/Booking/BookHearingTests.cs
UI.AutomationTests/Admin/Booking/CancelHearingTests.cs
UI.AutomationTests/Admin/Booking/CancelMultiDayHearingTests.cs
UI.AutomationTests/Admin/Booking/CreatingMultiDayHearingIndividualDateTests.cs
UI.AutomationTests/Admin/Booking/CreatingMultiDayHearingTests.cs
UI.AutomationTests/Admin/Booking/EditBookingTest.cs
UI.AutomationTests/Admin/Booking/EditMultiDayHearingTests.cs
UI.AutomationTests/Admin/BookingList/SearchForHearingTests.cs
UI.AutomationTests/Admin/WorkAllocation/AllocateHearingTests.cs
UI.AutomationTests/Admin/WorkAllocation/ManageTeamTests.cs
UI.AutomationTests/Admin/WorkAllocation/WorkHourTests.cs
UI.AutomationTests/Video/AddParticipantsPostBookingTests.cs
UI.AutomationTests/Video/EndToEndTest.cs
UI.AutomationTests/Video/JudgeTests.cs
UI.AutomationTests/Video/QuickLinkUserTests.cs
UI.AutomationTests/Video/StaffMemberTests.cs
azure-pipelines.sds.daily.yml
setup/data/seed_persons.sql
variables/shared.yaml

VIH-11033
There isa  60 minute limit on the agents for each job. The idea is to split the tests into categories and have each category run as it's own job as a workaround to the 60 minute limit

VIH-11033 split tests into categories

---

UI.AutomationTests/TestData/HearingTestData.cs
UI.AutomationTests/UI.AutomationTests.csproj
UI.AutomationTests/Video/JudgeTests.cs
UI.PageModels/UI.PageModels.csproj

Update api clients

---

UI.AutomationTests/Admin/Booking/EditMultiDayHearingTests.cs
UI.Common/Utilities/FeatureToggle.cs
UI.PageModels/Pages/Admin/Booking/HearingSchedulePage.cs

https://tools.hmcts.net/jira/browse/VIH-11090
Fixes for test failures on the staging environment
Updates to journeys when the feature flags are disabled

VIH-11090 Journey updates for when flags are disabled

---

UI.AutomationTests/Video/EndToEndTest.cs
UI.AutomationTests/Video/QuickLinkUserTests.cs
UI.PageModels/Pages/Video/Participant/JudgeWaitingRoomPage.cs
UI.PageModels/Pages/Video/QuickLink/QuickLinkJoinYourHearingPage.cs

https://tools.hmcts.net/jira/browse/VIH-11184
skips most of the admin webs journey (except getting the quicklink uri) and validates the QL is in the waiting room by checking their waiting room status, rather than the toastr which is flakey

VIH-111184 refactored quicklinks 

---

UI.AutomationTests/Video/EndToEndTest.cs
UI.Common/Utilities/FeatureToggle.cs
UI.PageModels/Pages/Video/Participant/JudgeWaitingRoomPage.cs

https://tools.hmcts.net/jira/browse/VIH-11175

VIH-11175 Added IM feature flag to end2end test

---

UI.AutomationTests/Drivers/LocalChromeVhDriver.cs
UI.AutomationTests/UI.AutomationTests.csproj
UI.AutomationTests/Video/JudgeTests.cs
UI.AutomationTests/appsettings.json
UI.PageModels/Pages/VhPage.cs
UI.PageModels/Pages/Video/Participant/JudgeWaitingRoomPage.cs

TBC
Remove chrome for testing and stick to the web driver manager to be responsible for downloading the correct binaries for requested browsers

VIH-11184 Remove chrome for testing

---

UI.AutomationTests/Admin/AdminWebUITest.cs
UI.AutomationTests/CommonUiTest.cs
UI.AutomationTests/Models/VideoWebParticipant.cs
UI.AutomationTests/Reporters/TestReporter.cs
UI.AutomationTests/TestData/HearingTestData.cs
UI.AutomationTests/Video/JoinAsJvsEndpointTest.cs
UI.AutomationTests/Video/QuickLinkUserTests.cs
UI.AutomationTests/Video/VideoWebUiTest.cs
UI.AutomationTests/appsettings.json
UI.Common/Configuration/EnvironmentConfigSettings.cs
UI.PageModels/Extensions/DriverExtensions.cs
UI.PageModels/Extensions/ScreenshotUtil.cs
UI.PageModels/Pages/PexipInfinityWeb/PexipWebLandingPage.cs
UI.PageModels/Pages/VhLoginPage.cs
UI.PageModels/Pages/VhPage.cs
UI.PageModels/Pages/Video/Participant/JudgeHearingRoomPage.cs
UI.PageModels/Pages/Video/Participant/JudgeWaitingRoomPage.cs
UI.PageModels/Utilities/ScreenshotCollector.cs
azure-pipelines.sds.daily.yml
pipelines/templates/run-ui-test.yaml
variables/shared.yaml

VIH-11189
* Add test to log in as JVS
* Split report so each user is a node in the HTML test report

VIH-11189 Add test to log in as JVS

---

UI.PageModels/Pages/VhPage.cs

https://tools.hmcts.net/jira/browse/VIH-10524
added wrapper for webdriver exceptions so we can see at the top level which page and element was unreachable

VIH-10524 More detail for exceptions

---

UI.AutomationTests/TestData/HearingTestData.cs
UI.AutomationTests/Video/JoinAsJvsEndpointTest.cs
UI.AutomationTests/Video/QuickLinkUserTests.cs
UI.PageModels/Dtos/BookingParticipantDto.cs
UI.PageModels/Pages/Admin/Booking/BookingDetailsPage.cs
UI.PageModels/Pages/Admin/Booking/ParticipantsPage.cs
UI.PageModels/Pages/Admin/Booking/SummaryPage.cs
UI.PageModels/Pages/Video/Participant/JudgeHearingRoomPage.cs
UI.PageModels/Pages/Video/Participant/JudgeWaitingRoomPage.cs

VIH-11150
Add Defence Advocate to JVS test Check if participant page is in edit mode for admin web

VIH-11150 Add Defence Advocate to JVS test Check if participant page is in edit mode for admin web

---

UI.AutomationTests/Admin/Booking/BookHearingTests.cs
UI.AutomationTests/Admin/Booking/EditBookingTest.cs
UI.AutomationTests/Video/AddParticipantsPostBookingTests.cs
UI.AutomationTests/Video/EndToEndTest.cs
azure-pipelines.sds.daily.yml

make logging in a parallel task to speed ui tests
VIH-11184
Update journey for special measure tests
Run log in with a parallel loop to speed up test run

VIH-11184 Update journey for special measure tests

---

UI.AutomationTests/Video/JudgeTests.cs
UI.PageModels/Pages/Video/Participant/ConsultationRoomPage.cs
UI.PageModels/Pages/Video/Participant/JudgeWaitingRoomPage.cs

VIH-11184
add JoH consultation room to the Judge journey

VIH-11184 add JoH consultation room to the Judge journey

---

UI.AutomationTests/Video/QuickLinkUserTests.cs
UI.PageModels/Pages/Video/Participant/JudgeHearingRoomPage.cs
UI.PageModels/Pages/Video/Participant/ParticipantHearingRoomPage.cs

VIH-11184
Assert on hand raised and lowered

VIH-11184 Assert on hand raised and lowered

---

UI.AutomationTests/CommonUiTest.cs
UI.AutomationTests/Drivers/LocalChromeVhDriver.cs
UI.AutomationTests/TestData/HearingTestData.cs
UI.AutomationTests/UI.AutomationTests.csproj
UI.AutomationTests/Video/AddParticipantsPostBookingTests.cs
UI.AutomationTests/Video/EndToEndTest.cs
UI.AutomationTests/Video/JoinAsJvsEndpointTest.cs
UI.AutomationTests/Video/VideoWebUiTest.cs
UI.PageModels/Dtos/BookingParticipantDto.cs
UI.PageModels/Pages/Video/Participant/JudgeHearingRoomPage.cs
UI.PageModels/Pages/Video/Participant/ParticipantHearingRoomPage.cs

[VIH-11184](https://tools.hmcts.net/jira/browse/VIH-11184)
* fix locator for hand raised icon
* Provide fake video streams instead of default green circles

VIH-11184 fix locator for hand raised icon

---

UI.AutomationTests/CommonUiTest.cs
UI.AutomationTests/Drivers/LocalChromeVhDriver.cs
UI.AutomationTests/Drivers/RemoteChromeVhDriver.cs
UI.AutomationTests/appsettings.json
UI.PageModels/Pages/Admin/Booking/BookingDetailsPage.cs

VIH-11241
Update locator path for

VIH-11241 Update locator for VAP link

---

UI.AutomationTests/CommonUiTest.cs
UI.AutomationTests/Drivers/LocalChromeVhDriver.cs
UI.AutomationTests/Drivers/RemoteChromeVhDriver.cs

VIH-0000 Fix fake device stream

---

UI.AutomationTests/Admin/AdminWebUITest.cs
UI.AutomationTests/Admin/Booking/BookHearingTests.cs
UI.AutomationTests/Admin/Booking/EditMultiDayHearingTests.cs
UI.AutomationTests/CommonUiTest.cs
UI.AutomationTests/EmailNotifications/EmailNotificationService.cs
UI.AutomationTests/Video/EndToEndTest.cs
UI.AutomationTests/Video/VideoWebUiTest.cs

https://tools.hmcts.net/jira/browse/VIH-10419

VIH-10419 Notify assertions

---

UI.AutomationTests/TestData/HearingTestData.cs
UI.AutomationTests/UI.AutomationTests.csproj
UI.Common/Utilities/FeatureToggle.cs
UI.PageModels/UI.PageModels.csproj

https://tools.hmcts.net/jira/browse/VIH-11197
- Remove vodafone feature toggle
- Remove and replace references to Kinly

VIH-11197 Remove Vodafone toggle and Kinly supplier

---

UI.AutomationTests/UI.AutomationTests.csproj
UI.AutomationTests/Video/AddParticipantsPostBookingTests.cs
UI.PageModels/Pages/Admin/Booking/BookingConfirmationPage.cs

VIH-11248
Update UI assertions since participant role of added participant is not a witness

VIH-11248 Update UI assertions for participant added after booking

---

pipelines/templates/run-ui-test.yaml

VIH-0000 fix template param

---

UI.AutomationTests/Video/EndToEndTest.cs
UI.AutomationTests/Video/VideoWebUiTest.cs
UI.PageModels/Pages/Video/Participant/GetReadyForTheHearingIntroductionPage.cs

https://tools.hmcts.net/jira/browse/VIH-11228

VIH-11228 Added rep skip self test journey to end2end

---

UI.AutomationTests/Drivers/LocalChromeVhDriver.cs
UI.AutomationTests/Video/AddParticipantsPostBookingTests.cs

VIH-11184
* update screen resolution for local chrome driver so that the screenshots contain more information
* Ensure the booking was successful in `should_add_new_participant_after_booking` to capture issues sooner

VIH-11184 update screen resolution for local chrome driver so that the screenshots contain more information

---

UI.AutomationTests/Admin/Booking/HearingTest.cs
UI.AutomationTests/CommonUiTest.cs
UI.AutomationTests/EmailNotifications/EmailNotificationService.cs
UI.AutomationTests/Video/DailyProdCheck.cs
UI.AutomationTests/Video/VideoWebUiTest.cs
UI.AutomationTests/appsettings.json
UI.Common/Configuration/EnvironmentConfigSettings.cs
UI.PageModels/Dtos/BookingDto.cs
UI.PageModels/Dtos/BookingParticipantDto.cs
UI.PageModels/Pages/Admin/Booking/BookingDetailsPage.cs
UI.PageModels/Pages/Admin/Booking/ParticipantsPage.cs
UI.PageModels/Pages/Admin/Booking/SummaryPage.cs
UI.PageModels/Pages/Admin/BookingListPage.cs
UI.PageModels/Pages/VhPage.cs
UI.PageModels/Pages/Video/Participant/JudgeHearingListPage.cs
UI.PageModels/Pages/Video/Participant/JudgeHearingRoomPage.cs
UI.PageModels/Pages/Video/Participant/ParticipantHearingListPage.cs
UI.PageModels/Pages/Video/VideoWebLogoutPage.cs
azure-pipelines.prod.smoke.test.yml
pipelines/templates/run-ui-test.yaml
setup/data/seed_generic_judiciary.sql
variables/prod.yaml
variables/shared.yaml

VIH-11149
* Confirming booking is successful in booking journey Remove the email body from console log
* Update sign out action to confirm sign out step
* Do not attempt to remove hearings generated from UI test if the environment is production, Prod APIs are not accessible
* Include the Pexip Sip Address Stem in the config to help build join url

VIH-11149 add a smoke test to run in prod

---

UI.AutomationTests/Reporters/TestReporter.cs
UI.AutomationTests/UI.AutomationTests.csproj
UI.AutomationTests/Video/AddParticipantsPostBookingTests.cs
UI.PageModels/Pages/Video/Participant/CommonWaitingRoomPage.cs
UI.PageModels/Pages/Video/Participant/JudgeHearingRoomPage.cs
UI.PageModels/Pages/Video/Participant/JudgeWaitingRoomPage.cs
UI.PageModels/UI.PageModels.csproj

VIH-11273
Cover the scenario of late joiners (i.e. participants who join a hearing after it is in session)
participant added after booking joins after hearing has started

VIH-11273 participant added after booking joins after hearing has started

---

UI.AutomationTests/UI.AutomationTests.csproj
UI.AutomationTests/Video/AddParticipantsPostBookingTests.cs
UI.PageModels/Pages/Video/Participant/JudgeHearingRoomPage.cs

VIH-11273
Update assertions for participant joining a hearing already in session

VIH-11273 Update assertions for participant joining a hearing already in session

---

UI.AutomationTests/Video/VideoWebUiTest.cs

VIH-11184
check participant type to ensure confirmation step is only done for AD users

VIH-11184 check participant type to ensure confirmation step is only done for AD users

---

UI.PageModels/Pages/Admin/Booking/BookingDetailsPage.cs

VIH-11184
fix expected flow for when editing a booking with special measures turned off

VIH-11184 fix expected flow for when editing a booking with special measures turned off

---

azure-pipelines.sds.daily.demo.yml

add demo on schedule

---

UI.PageModels/Pages/Video/Participant/JudgeHearingRoomPage.cs
setup/data/seed_persons.sql

VIH-11184
Update locator for checking if participant has joined hearing in session
Update seed data output

VIH-11184 Update locator for checking if participant has joined hearing in session

---

UI.AutomationTests/Admin/Booking/BookHearingTests.cs
UI.AutomationTests/Admin/Booking/EditBookingTest.cs
UI.AutomationTests/Admin/Booking/HearingTest.cs
UI.AutomationTests/Mappers/HearingRoleCodeMapper.cs
UI.AutomationTests/TestData/HearingTestData.cs
UI.AutomationTests/Video/EndToEndTest.cs
UI.AutomationTests/Video/ScreenedParticipantTests.cs
UI.AutomationTests/Video/VideoWebUiTest.cs
UI.PageModels/Dtos/BookingDto.cs
UI.PageModels/Dtos/BookingParticipantDto.cs
UI.PageModels/Dtos/ScreeningDto.cs
UI.PageModels/Dtos/ScreeningEntityDto.cs
UI.PageModels/Dtos/ScreeningParticipantDto.cs
UI.PageModels/Dtos/VideoAccessPointsDto.cs
UI.PageModels/Pages/Admin/Booking/BookingDetailsPage.cs
UI.PageModels/Pages/Admin/Booking/HearingDetailsPage.cs
UI.PageModels/Pages/Admin/Booking/SpecialMeasuresPage.cs
UI.PageModels/Pages/Admin/Booking/SummaryPage.cs
UI.PageModels/Pages/VhAdminWebPage.cs
UI.PageModels/Pages/Video/Participant/ConsultationRoomPage.cs

https://tools.hmcts.net/jira/browse/VIH-11118
- Add tests for special measures
- - Booking a hearing with screened participants
- - Editing a hearing with screened participants
- - Running a consultation with screened participants
- Restore a removed test
- Refactoring of common code

VIH-11118 Add tests for special measures

---

UI.AutomationTests/Video/EndToEndTest.cs
UI.Common/Utilities/FeatureToggle.cs

https://tools.hmcts.net/jira/browse/VIH-11327
Remove the conditional check for testing instant messages as the feature toggle does not exist in video web, so always test them

VIH-11327 Remove check for IM enhancements

---

UI.AutomationTests/Video/QuickLinkUserTests.cs
UI.AutomationTests/Video/RepTests.cs
UI.PageModels/Pages/Video/Participant/CommonWaitingRoomPage.cs
UI.PageModels/Pages/Video/Participant/ParticipantWaitingRoomPage.cs
UI.PageModels/Pages/Video/Participant/TestingEquipmentPage.cs

VIH-11184
Ensure self test video has completed before moving on for skip self test journey
Clear notifications for participants added in QL test

VIH-11184 Update assertions and journey for self test

---

UI.AutomationTests/Admin/Booking/EditMultiDayHearingTests.cs
UI.AutomationTests/TestData/HearingTestData.cs
setup/data/seed_persons.sql

https://tools.hmcts.net/jira/browse/VIH-11353
The interpreter tests try to add a participant which has since been deleted (suspect the anonymisation scheduler job is the culprit). Fix by re-creating the account with a username containing a different prefix ("auto" rather than "Automation") which is exempt from deletion by the anonymisation job

VIH-11363 Fix failing tests
